server:
  port: 8765
spring:
  application:
    name: Employee_MobileRelationshipApplication
  datasource:      
    url: jdbc:mysql://localhost:3306/one_to_one_uni
    username: root
    password: Tiger2143@+%
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  
      
        
        
        
   
      